# Generated by Django 5.1.4 on 2026-06-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_profile_shop_rules_servers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casereward',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Награда колеса', 'verbose_name_plural': 'Награды колеса'},
        ),
        migrations.AlterModelOptions(
            name='casespin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Прокрутка бонусного колеса', 'verbose_name_plural': 'Прокрутки бонусного колеса'},
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_spin_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее открытие бонуса'),
        ),
    ]
